// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: model/ticker.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_model_ticker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_model_ticker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_model_ticker_proto_rawDescGZIP(), []int{0}
}

func (x *Ticker) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Ticker) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Ticker) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Ticker) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Ticker) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TickerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*Ticker              `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerList) Reset() {
	*x = TickerList{}
	mi := &file_model_ticker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerList) ProtoMessage() {}

func (x *TickerList) ProtoReflect() protoreflect.Message {
	mi := &file_model_ticker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerList.ProtoReflect.Descriptor instead.
func (*TickerList) Descriptor() ([]byte, []int) {
	return file_model_ticker_proto_rawDescGZIP(), []int{1}
}

func (x *TickerList) GetTickers() []*Ticker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type TickerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerMessage) Reset() {
	*x = TickerMessage{}
	mi := &file_model_ticker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerMessage) ProtoMessage() {}

func (x *TickerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_model_ticker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerMessage.ProtoReflect.Descriptor instead.
func (*TickerMessage) Descriptor() ([]byte, []int) {
	return file_model_ticker_proto_rawDescGZIP(), []int{2}
}

func (x *TickerMessage) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *TickerMessage) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *TickerMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TickerMessage) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *TickerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TickerMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*TickerMessage       `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerMessageList) Reset() {
	*x = TickerMessageList{}
	mi := &file_model_ticker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerMessageList) ProtoMessage() {}

func (x *TickerMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_model_ticker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerMessageList.ProtoReflect.Descriptor instead.
func (*TickerMessageList) Descriptor() ([]byte, []int) {
	return file_model_ticker_proto_rawDescGZIP(), []int{3}
}

func (x *TickerMessageList) GetTickers() []*TickerMessage {
	if x != nil {
		return x.Tickers
	}
	return nil
}

var File_model_ticker_proto protoreflect.FileDescriptor

const file_model_ticker_proto_rawDesc = "" +
	"\n" +
	"\x12model/ticker.proto\x12\x06ticker\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x06Ticker\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"last_price\x18\x04 \x01(\x01R\tlastPrice\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"6\n" +
	"\n" +
	"TickerList\x12(\n" +
	"\atickers\x18\x01 \x03(\v2\x0e.ticker.TickerR\atickers\"\x8e\x01\n" +
	"\rTickerMessage\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"last_price\x18\x04 \x01(\x01R\tlastPrice\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"D\n" +
	"\x11TickerMessageList\x12/\n" +
	"\atickers\x18\x01 \x03(\v2\x15.ticker.TickerMessageR\atickersB,Z*roselabs.mx/ftso-data-sources/proto/tickerb\x06proto3"

var (
	file_model_ticker_proto_rawDescOnce sync.Once
	file_model_ticker_proto_rawDescData []byte
)

func file_model_ticker_proto_rawDescGZIP() []byte {
	file_model_ticker_proto_rawDescOnce.Do(func() {
		file_model_ticker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_ticker_proto_rawDesc), len(file_model_ticker_proto_rawDesc)))
	})
	return file_model_ticker_proto_rawDescData
}

var file_model_ticker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_ticker_proto_goTypes = []any{
	(*Ticker)(nil),                // 0: ticker.Ticker
	(*TickerList)(nil),            // 1: ticker.TickerList
	(*TickerMessage)(nil),         // 2: ticker.TickerMessage
	(*TickerMessageList)(nil),     // 3: ticker.TickerMessageList
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_model_ticker_proto_depIdxs = []int32{
	4, // 0: ticker.Ticker.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: ticker.TickerList.tickers:type_name -> ticker.Ticker
	2, // 2: ticker.TickerMessageList.tickers:type_name -> ticker.TickerMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_ticker_proto_init() }
func file_model_ticker_proto_init() {
	if File_model_ticker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_ticker_proto_rawDesc), len(file_model_ticker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_ticker_proto_goTypes,
		DependencyIndexes: file_model_ticker_proto_depIdxs,
		MessageInfos:      file_model_ticker_proto_msgTypes,
	}.Build()
	File_model_ticker_proto = out.File
	file_model_ticker_proto_goTypes = nil
	file_model_ticker_proto_depIdxs = nil
}
